name: Build Wheels

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          # Define which architectures to build for each OS
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: universal2
          CIBW_ARCHS_WINDOWS: AMD64

      - name: Collect wheels into dist/  # make the wheels in the format that the publish to pypi expects 
        run: |
          mkdir -p dist
          cp wheelhouse/*.whl dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist/*.whl

  upload_to_release:
    runs-on: ubuntu-latest
    needs: build_wheels
    if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'  # On tag or manual
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./all-wheels/
          merge-multiple: true

      - name: Upload wheels to release
        run: |
          gh release upload ${{ github.ref_name }} ./all-wheels/*.whl --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}